plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
remote_theme: NightHammer1000/moonwalk
title: false
